apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ include "helm.fullname" . }}-secret
  namespace: test
spec:
  encryptedData:
    secrets.yaml: AgCWU1iTMfbuV3R6LJKCiwrOLglrVIagTYkrvc1Yr5RxIC8ohv9mb3hkD6M60Z4RUhOTI2KFCZRDvIILOKy4rXQyaFxpEr2J+P4HfHm1obqY2qXpspWXrY8HGAIP3J16O6ospH6Y/PSV7FvXK2D2e4nWJz44Tz5F/vjSEOgvwN2WKemKNY/cGig/k9+F2h8xTInwGIhl9gAEI/SxgIZxXTJEd88ifgwQ8D6+txisvHnhG0oFra7c0EKTLUJPP94Gk2d9Y9ujtr020+Mj28ZR8wYmWctwG5a3OzIcYp4eulPNjAs0vTtn43S/6K0DLDQau6B1RrGO5vDAa8y+q5Bd9CFGrNFM/gS9rWq7cQtoXKOWKMusOD8v/991B0gK/sJCXDI/X/WI3fzdRXxVxDmBcZB3Q27AJKju6aKIWbAk50AGjliY/kA6NMNjHbm0A7vZdVEgAsgQfb+yd4dMNStv7YCldnwT/gGDNhmS0d4UgWEzTrSZKg2ZhnpFF2c0A+9jfKk/vWL38eWKg9i0WpNzwG7rqAFU2WYKpeB6ohaaBvF2X6eWrVDKxHDX/GYhp3m5lJeTfafrI5vQDgJEbOVfayO/oQQKjM3lZsiO0FEeSyNi8KoU8Df1Z2azw3fW51p1vXQ8Q/o7mDGDwFwqPMQoXHVqJ3WiiLeumrcTLw7SeObbjmr8L0HCpjg0zij5h8LofsJVpE4R2lB6tP+TplNYmUVy/Ia7G6L4qtCMnQbp3IMWjAFaNtP5El4VFARa+Mf3Je+NE5+RRWz6hY+QZDUJLPhxLhqwkH0oPxQiwMQ+ZGrD5olXKmK9PFsUzuSfzpQOm077euBlxAjI8jHdyjMbgyE5916zQoKYoWddGIdvpQZyTXe2ODeE+MhrJRAcZSKH
  template:
    metadata:
      creationTimestamp: null
      name: config-server-sealed-secrets
      namespace: test

